### ISSUE TITLE
getRowDimension()

### ISSUE THREAD

**Issue by haietza** [JaysGitLab/cs5666-spr17-javatrix-c2m2#27]
Get row dimension.

**Comment by haietza** [comment]
@caldwellc1 @KaraBeason So, I learned something valuable here - I had been creating new branches off my previously worked on branches, instead of off master. This branch accidentally got merged in because the code was included in a different pull request that was approved. I can't re-open the pull request because the code has already been merged into master. However I'm going to leave this issue open until one of you is able to review the code and approve it. If you can't approve the pull request #57, then just @mention me here and let me know.

Good lesson learned - I will start branching off master from now on! Sorry for the confusion!

**Comment by KaraBeason** [comment]
@haietza Ah, that's interesting!  I was wondering what happened with the PR, but I figured it was something to do with that.  Thanks for letting us know!
