### ISSUE TITLE
Matrix(double[] vals, int m)

### ISSUE THREAD

**Issue by haietza** [JaysGitLab/cs5666-spr17-javatrix-c2m2#3]
Construct a matrix from a one-dimensional packed array

**Comment by caldwellc1** [comment]
I can't figure out how to get the test working properly. I think the code is all good but I just can't auto test it.

**Comment by haietza** [comment]
@caldwellc1 You could iterate through the vals array that is passed as a parameter and the returned Javatrix array and test that each element is the same. You could also add the invalid test to make sure the exception is returned if vals.length is not a multiple of m.

**Comment by haietza** [comment]
@caldwellc1 Would you like me to write the code for the test and push it up for you guys to review?

**Comment by haietza** [comment]
@caldwellc1 Can you add a comment as to why this issue was changed from medium to hard, for our reflection on our team estimates please? Thanks!
