### ISSUE TITLE
times(double s)

### ISSUE THREAD

**Issue by haietza** [JaysGitLab/cs5666-spr17-javatrix-c2m2#45]
Multiply a matrix by a scalar, C = s*A

**Comment by caldwellc1** [comment]
@haietza @KaraBeason My code is failing my test. Everything looks ok to me so I could use a fresh pair of eyes on it.

**Comment by haietza** [comment]
@caldwellc1 So, this method is actually supposed to create a new Javatrix object (C) that contains elements that are the products of the elements from the calling Javatrix object (A) multiplied by the parameter (s). You will want to create a new Javatrix object in the method and return it - not adjust the values of the calling object using 'this'. Your test is returning a null pointer exception because you are trying to pass in a Javatrix object that has not been created yet [actual = actual.times(scaler);]. You have to use a constructor to create actual with some values first, then create another Javatrix object by calling the times method on 'actual'. Let me know if this makes sense :).

**Comment by caldwellc1** [comment]
@haietza Haha, I was looking at the requirements for timesEqual instead of just times! Also, no it doesn't make sense since I did the wrong thing. I'm not sure what you mean by it's returning a null pointer. On the bases it's the Equal's one how has it not been created yet?

**Comment by haietza** [comment]
@caldwellc1 I know - I keep confusing the base method with the Equals version too! Especially since they both return objects! So I edited the code and pushed it back up to your branch - I thought it might be easier for you to see in code than me trying to explain here (we can discuss in person tomorrow in class, if that helps). You have to first create the Javatrix actual object by passing in the first matrix (so it exists) before you can call the times method on it. Trying to create the object by calling the times method on the object that has not been created yet causes the null pointer exception - because the 'actual' variable still has not been initialized with a Javatrix object yet. It has to exist before you can call that function on it, since it is not a static method. I hope this helps!
