### ISSUE TITLE
timesEquals(double s)

### ISSUE THREAD

**Issue by haietza** [JaysGitLab/cs5666-spr17-javatrix-c2m2#47]
Multiply a matrix by a scalar in place, A = s*A

**Comment by caldwellc1** [comment]
@haietza @KaraBeason The test is failing. The value being returned is 10.889999 where it should return 3.3, so I'm not sure where it's messing up at since it's not even a double mult of 3.3.

**Comment by haietza** [comment]
@caldwellc1 You need to initialize the 'actual' object with the matrix before you multiply its elements by the scalar - otherwise you are doing the multiplication twice on the object (10.89 is 3.3 * 3.3). I changed the code to make this fix, as well as made a few spelling corrections. Take a look and let me know if you have questions - thanks!

**Comment by caldwellc1** [comment]
@haietza Ah, for some reason I was multiplying 3.3 times 3 so I though if it was multiplying twice it would equal 9.9. Thanks, it's always nice to have another pair of eyes on things especially since I often miss spell things which causes problems.
