### ISSUE TITLE
Matrix(int m, int n, double s)

### ISSUE THREAD

**Issue by haietza** [JaysGitLab/cs5666-spr17-javatrix-c2m2#5]
Construct an m-by-n constant matrix.

**Comment by caldwellc1** [comment]
I'm not sure if it would be better to have the one who reviews it to merge or the person who made it to merge the branches. Let me know what you think.

**Comment by haietza** [comment]
I think the person who wrote the code should handle the merge. The reviewer should mark the pull request as approved, so the programmer knows it is okay to move forward with the merge. Does that sound okay? @caldwellc1 @KaraBeason

**Comment by haietza** [comment]
@caldwellc1 @KaraBeason Also, what do you guys think about having the programmer who wrote the code and does the merge into master move the issue to the Completed board? That way it's not marked complete until it's been approved and merged.

**Comment by haietza** [comment]
@caldwellc1 @KaraBeason Test method names fixed on this.

**Comment by caldwellc1** [comment]
How should we make it as approved? Should we have a label or just comment?

**Comment by haietza** [comment]
@caldwellc1 I've not done it myself, but here is github documentation that should help: https://help.github.com/articles/approving-a-pull-request-with-required-reviews/

**Comment by KaraBeason** [comment]
@haietza @caldwellc1 when you're on the pull request there's a green button upper right corner that says "add your review", click and one of the options is "Approve".
